### ISSUE TITLE
Discrepencies between denormalized and merged grants tables

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#33]
These grants are in the normalized table, but not in the merged table:

# A tibble: 5 x 2
  id          name                                                                            
  <chr>       <chr>                                                                           
1 syn9774959  From Mechanism to Population - Modeling HPV-related Oropharyngeal Carcinogenesis
2 syn9775665  CSBC U01 Project Boston University                                              
3 syn9775704  Intratumor heterogeneity underlying treatment resistance in HER2+ breast tumors 
4 syn17023185 ISB Heath Lab                                                                   
5 syn17084070 Phenotype Transitions in Small Cell Lung Cancer - CA215845

**Comment by bswhite** [comment]
1. syn9774959 is grant CA182915; PI: Meza. The NCI asked us to remove this grant. It was from a different program (BTG). None of its pubs, datasets, etc. should show up in the portal. 

2. syn9775665 CSBC U01 Project Boston University is grant CA182898. It has been renamed:
Uncoupling obesity from breast cancer in African American women
and should be kept. We sometimes have temporary names like this, which highlights that we should be using grant numbers as ids (i.e., CA182898). I will create a separate GitHub issue for this.

3. syn9775704 is CA195469. This should be in the portal. It is an old "ICBP" grant. But we continue to track some of these. Information about it is included in the attached file Portal-GrantsMerged.

[Portal-GrantsMerged.xlsx](https://github.com/Sage-Bionetworks/csbc-pson-dcc/files/4553753/Portal-GrantsMerged.xlsx)

4. ISB Heath Lab should be dropped. This is an odd ball grant that arose because the PI moved institutions. Evidently when he did he was assigned a new grant number. That new grant number is CA217655 (Steady States and Cellular Transitions Associated with Carcinogenesis and Tumor progression). You should find no datasets, pubs, etc assigned to "ISB Heath Lab"; these should have instead been moved to the "Steady States ..." grant.

5. The grant with name "Phenotype Transitions in Small Cell Lung Cancer - CA215845" was somehow created redundantly with one named "Phenotype Transitions in Small Cell Lung Cancer" (both of which have grant number CA215845). You should find no associated pubs, datasets, files, etc with the former, which should have instead been assigned to the latter.

**Comment by andrewelamb** [comment]
This seems to not be an issue now, either these got removed from the normalized table, or added to the merged table. @jaeddy @bswhite
