### ISSUE TITLE
Dataset table has a duplicated datatset

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#46]
The merged dataset table has a dataset that is in two rows:

````
syn21889770 phs001231.v2.p1
````
It seems to be associated with two different publications, which may be the issue?

**Comment by jaeddy** [comment]
Hmm... yeah, I would suspect publication as the culprit — otherwise `distinct()` should take care of duplicates. We haven't looked at making publication a list column, because the goal is to present the pub in which the dataset was first reported. Maybe we can just check the publication date and keep whichever came first.

**Comment by jaeddy** [comment]
I deleted the record with the more recent publication (i.e., [PMID:27479327](https://pubmed.ncbi.nlm.nih.gov/27479327/). However, I'd like to revisit this issue at some point in the future: the dataset in question is actually [NeuroLINCS](https://www.ncbi.nlm.nih.gov//bioproject/PRJNA349770), which almost certainly wasn't _generated_ via CSBC/PS-ON funding. Moving forward, we might want to capture/index any _usage_ of datasets in published consortia research.
