### ISSUE TITLE
Migrate all linked NCBI-linked dataset folders to Portal DB project

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#48]
The entities in the [normalized dataset table](https://www.synapse.org/#!Synapse:syn21889931/tables/) are based on mock entities that I've created in [this folder](https://www.synapse.org/#!Synapse:syn21889510).

@bswhite has updated the data in the [merged datasets table](https://www.synapse.org/#!Synapse:syn21897968/tables/
) such that synIDs point to the appropriate folders across various Synapse projects. These folders are now named according to the associated NCBI **BioProject** accession.

What we want to do is identify and **move** (not copy) these folders to the **CSBC PS-ON DB** project [`datasets` folder](https://www.synapse.org/#!Synapse:syn21889510). We should subsequently update the [normalized dataset table](https://www.synapse.org/#!Synapse:syn21889931/tables/) such that it's a **Folder View** of [`datasets`](https://www.synapse.org/#!Synapse:syn21889510) (plus a few additional items that need to be included in the view scope).

Similar to the reverse-ETL approach, we'd ideally want an isolated test project (or "dry run" mode) to test how the script would work before running on the real entities.

**Comment by andrewelamb** [comment]
@jaeddy

Since this will be a file/folder view we will need to update/add annotations on these entities.

For example one of your mock entities look like this:


grantId | syn9773338
displayName | GSE100274
overallDesign | NA
fullName | NA
synapseLocation | syn21796552
publicationId | syn21648934

One of the folders references in the merged dataset view:

grantName | Dynamics of Gene and Isoform Regulation during EMT and tumor progression
teamProfileId | 3355678
numOfFiles | 0
grantId | syn9775689
consortium | CSBC
abstract | NA
institution | Massachusetts Institute of Technology \| Beth Israel Deaconess Hospital \| Massachusetts General Hospital
investigator | NA
fundingAgency | NCI
theme | Metastasis, Heterogeneity
grantType | U01
synapseTeam | 3355678
grantNumber | CA184897
numOfContributors | 0
centerName | CSBC U01 Project MIT BIMDC MGH

How should I go about doing this update? Should I preserve the current annotations?

**Comment by bswhite** [comment]
@andrewelamb and @jaeddy -- I still think this (migration to a single folder) will be convenient, but note that the file/folder view that it will facilitate may not be useful. We use tables, including for datasets, in part because tables support long text fields (needed for dataset summary/description and overall design) and views do not.

@andrewelamb please let us (@vpchung and @jaybee84 ) know when you start this migration -- we are currently hunting for datasets in their respective grant folders and would like to know if we should start looking elsewhere.

**Comment by jaeddy** [comment]
@andrewelamb I think we'll need to abandon the current dataset entities and tables in the [Portal DB](https://www.synapse.org/#!Synapse:syn21498902). I'd rename the [`datasets` folder](https://www.synapse.org/#!Synapse:syn21889510) to `datasets_old` in case we need anything there, then move the referenced folders into a new `datasets` folder. Once everything is in the same place, we can recreate the corresponding views/tables and clean up the annotations as needed.

@bswhite the way we've been handling long text for other entities is to keep them in a separate table (e.g., [`description_project`](https://www.synapse.org/#!Synapse:syn21868407/tables/)), then these get added back into the merged table. I think views will be convenient for the auto-updating when new content is added — but we obviously still have some sorting out to do with the overall pipeline.

@bswhite/@vpchung/@jaybee84 - as long as you're working from the merged datasets table (as I expect @andrewelamb will be), all of the folder links should still work. When the folders are moved, they'll keep the same Synapse ID.

**Comment by andrewelamb** [comment]
@jaeddy @bswhite 

Right now I am copying the entities into a test folder to work on. It looks like I won't be able to move all the entities due to permissions issues when we decide to really do this.

**Comment by andrewelamb** [comment]
@jaeddy Could you clarify what you mean by "clean up the annotations"?

Should i preserve all existing annotations? Should I replace all the annotations with the values in the merged dataset table? Something in between?

**Comment by andrewelamb** [comment]
@jaeddy @bswhite

I don't have the correct permissions to move these entities:

"syn11510898" "syn7248581"  "syn7248583"  "syn7248584"  "syn7248585"  "syn7248586"  "syn7248591"  "syn7248592"  "syn9697791"

**Comment by bswhite** [comment]
@andrewelamb do you mind if we don't move these? These are a special case -- they are the PS-ON Cell Line datasets. 

Note that they are all included in one Synapse project -- syn7248578. Though this may not be helpful to you because there are several other folders within that project that you should not include as datasets / data files:
syn17096714
syn17096709
syn11205984

**Comment by andrewelamb** [comment]
The plan was to use a file/folder view to manage these, and  propagate changes made the the merged dataset table to the annotations of these files/folders. @jaeddy what do you think?

**Comment by andrewelamb** [comment]
The other way of doing this would be to create some placeholder entities in the datasets folder that are referenced by the merged dataset table, instead of the actual datasets you don't want to move.
