### ISSUE TITLE
Grants missing in merged table

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#61]
These [grants](https://www.synapse.org/#!Synapse:syn21639712/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjM5NzEyIHdoZXJlIGlkIGluICgnc3luOTc3NDk1OScsICdzeW45Nzc1NjY1JywgJ3N5bjk3NzU3MDQnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=) should be in the [merged grants table](https://www.synapse.org/#!Synapse:syn21918972/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxOTE4OTcyIHdoZXJlIGdyYW50SWQgaW4gKCdzeW45Nzc0OTU5JywgJ3N5bjk3NzU2NjUnLCAnc3luOTc3NTcwNCcpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==)
They are referenced by a few projects.

**Comment by andrewelamb** [comment]
These are referenced by several publications as well

**Comment by andrewelamb** [comment]
Note these ids are in the normalized grants table, but not in the merged grants table:

1 syn9774959 
2 syn9775665 
3 syn9775704 
4 syn17023185
5 syn17084070

**Comment by jaeddy** [comment]
@andrewelamb

> 1 syn9774959
> 2 syn9775665
> 4 syn17023185

These all appear to be unused/deprecated Synapse projects. Please remove from the normalized grant table and any association tables.

> 3 syn9775704

This one might be legitimate and incorrectly missing from the merged table: https://grantome.com/grant/NIH/U01-CA195469-05

However, we don't seem to have any annotations [for the grant](https://www.synapse.org/#!Synapse:syn10142562/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjEwMTQyNTYyIFdIRVJFIGlkID0gJ3N5bjk3NzU3MDQnIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==). @bswhite any thoughts?

> 5 syn17084070

This one is a duplicate, and the version in the merged table is more up-to-date. Please remove from the normalized grant table and any association tables.

**Comment by andrewelamb** [comment]
@jaeddy The issue is the above four you said shoudl be removed are referenced at least by some [projects](https://www.synapse.org/#!Synapse:syn21645147/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjQ1MTQ3IHdoZXJlIGdyYW50SWQgaW4gKCdzeW45Nzc0OTU5JywgJ3N5bjk3NzU2NjUnLCAnc3luMTcwMjMxODUnLCAnc3luMTcwODQwNzAnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=)

**Comment by bswhite** [comment]
@andrewelamb ,

I'm just confirming James' responses above with a little more detail. That detail is included below mostly for my future reference.

In short, 
1. Remove syn9774959 and syn9775665 and any references to them in the projects, publications, datasets, tools, publications, and file tables/views.

2. Remove syn17023185 from datasets and projects, but confirm that it has no references in datasets, tools ,publications, and files. If it does, those should be changed to syn17083754. Additionally, syn17083754 should have one project associated with it.

3. As in (2), remove syn17084070 from datasets and projects, but confirm that it has no references in datasets, tools ,publications, and files. If it does, those should be changed to syn9775651. Additionally, syn9775651 should have one project associated with it.

3. syn9775704 should be in the grants table, you can find annotations for it in the attached excel sheet by looking up its grantNumber = CA195469.

More details follow ...


syn9774959 has grant name:
From Mechanism to Population: Modeling HPV-related Oropharyngeal Carcinogenesis
The PI is Meza and Shannon previously asked me to remove this grant because it is no longer active (email thread Re: CSBC publications + project themes).
Remove this grant and any associated projects, datasets, tools, publications, and file (views).

syn9775665 has (dummy) name:
CSBC U01 Project Boston University
I'm not sure why -- evidently we created this for some reason before we hand the name. I have renamed it
Uncoupling obesity from breast cancer in African American women
This also looks to be an old grant (Jennifer Couch is the PO); let's also remove.
Remove this grant and any associated projects, datasets, tools, publications, and file (views).

syn17023185 is the "ISB Heath Lab" grant. James Heath moved from Caltech to ISB, which I think confused things here. That other grant is syn17083754, with the possibly misspelled name Steady states and cellular transitions associated with carcinogenesis and tumorprogression. All references to syn17023185 in publications, tools, datasets, or files should instead be to syn17083754. The project associated with syn17023185 should be transferred to syn17083754, unless syn17083754 already has a project (which should be the same one).

syn9775704 is 
Intratumor heterogeneity underlying treatment resistance in HER2+ breast tumors
grantNumber is CA195469
As James said above, this should be included. Though it is actually an "ICBP" grant not a "CSBC." You can find information about it by looking up its grantNumber in the attached table.

syn17084070 is
Phenotype Transitions in Small Cell Lung Cancer - CA215845
all references to it should be replaced by
syn9775651
with name:
Phenotype Transitions in Small Cell Lung Cancer

[Portal-GrantsMerged.xlsx](https://github.com/Sage-Bionetworks/csbc-pson-dcc/files/4670670/Portal-GrantsMerged.xlsx)

**Comment by andrewelamb** [comment]
@bswhite @jaeddy I've done the following

Remove these rows:
[grants](https://www.synapse.org/#!Synapse:syn21639712/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjM5NzEyIHdoZXJlIGlkIGluICgnc3luOTc3NDk1OScsICdzeW45Nzc1NjY1JywgICdzeW4xNzAyMzE4NScsICdzeW4xNzA4NDA3MCcpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==)

[projects](https://www.synapse.org/#!Synapse:syn21645147/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjQ1MTQ3IHdoZXJlIGdyYW50SWQgaW4gKCdzeW45Nzc0OTU5JywgJ3N5bjk3NzU2NjUnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=)


Change the grant ids:

[projects](https://www.synapse.org/#!Synapse:syn21645147/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjQ1MTQ3IHdoZXJlIGdyYW50SWQgaW4gKCdzeW4xNzAyMzE4NScsICdzeW4xNzA4NDA3MCcpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==)

add syn9775704 to
[Merged Grants](https://www.synapse.org/#!Synapse:syn21918972/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxOTE4OTcyIHdoZXJlIGdyYW50SWQgaW4gKCdzeW45Nzc1NzA0JykiLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9)

**Comment by andrewelamb** [comment]
@bswhite @jaeddy @jaybee84 

Should I delete this [dataset](https://www.synapse.org/#!Synapse:syn21790736)?

And these [publications](https://www.synapse.org/#!Synapse:syn21682660/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjgyNjYwIHdoZXJlIGdyYW50SWQgaW4gKCdzeW45Nzc0OTU5JywgJ3N5bjk3NzU2NjUnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=)?

**Comment by bswhite** [comment]
@andrewelamb My earlier response was ambiguous, I am updating this comment.

Yes, remove the dataset PRJNA310350 [here](https://www.synapse.org/#!Synapse:syn21790736)
because we removed it's associated grant
syn9775665
formerly named CSBC U01 Project Boston University
then named Uncoupling obesity from breast cancer in African American women
as discussed [here](https://github.com/Sage-Bionetworks/csbc-pson-dcc/issues/61)

Similarly, you can remove the publications you [here](https://www.synapse.org/#!Synapse:syn21682660/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjgyNjYwIHdoZXJlIGdyYW50SWQgaW4gKCdzeW45Nzc0OTU5JywgJ3N5bjk3NzU2NjUnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=)
because they all correspond to the either the above U01 Project BU grant or to 
"From Mechanism to Population: Modeling HPV-related Oropharyngeal Carcinogenesis"
that we also agreed to remove in the above linked issue.

**Comment by andrewelamb** [comment]
@bswhite 

I've noticed that some publications that have one of the "bad" grant numbers are also associtated with a second "non-bad" grant number:

[grant_publications](https://www.synapse.org/#!Synapse:syn21682660/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjgyNjYwIHdoZXJlIHB1YmxpY2F0aW9uSWQgaW4gKCdzeW4yMTY0NTYxNScsICdzeW4yMTY0ODkxNCcsICdzeW4yMTY0NTYxNCcsICdzeW4yMTY0NTYxNicsICdzeW4yMTY0ODk2NicsICdzeW4yMTY0ODk4NicsICdzeW4yMTY0OTEzNCcsICdzeW4yMTY4MTgyMicsICdzeW4yMTY4MTQzNycsICdzeW4yMTY4MTYyNCcsICdzeW4yMTY4MTYyNicsICdzeW4yMTY0NTYxMicsICdzeW4yMTY0NTYxNycsICdzeW4yMTY0NTYxMycpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==)

[publications](https://www.synapse.org/#!Synapse:syn21868591/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODY4NTkxIHdoZXJlIHB1YmxpY2F0aW9uSWQgaW4gKCdzeW4yMTY0NTYxNScsICdzeW4yMTY0ODkxNCcsICdzeW4yMTY0NTYxNCcsICdzeW4yMTY0NTYxNicsICdzeW4yMTY0ODk2NicsICdzeW4yMTY0ODk4NicsICdzeW4yMTY0OTEzNCcsICdzeW4yMTY4MTgyMicsICdzeW4yMTY4MTQzNycsICdzeW4yMTY4MTYyNCcsICdzeW4yMTY4MTYyNicsICdzeW4yMTY0NTYxMicsICdzeW4yMTY0NTYxNycsICdzeW4yMTY0NTYxMycpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==)

I'm going to remove the "bad" grantId from these publicationIds, but leave the "good" one:
 ('syn21645615', 'syn21648914', 'syn21645614', 'syn21645616', 'syn21648966', 'syn21648986', 'syn21649134', 'syn21681822', 'syn21681437', 'syn21681624', 'syn21681626', 'syn21645612', 'syn21645617', 'syn21645613')

**Comment by andrewelamb** [comment]
I've deleted the "bad" publications and dataset. The publications above that had both a "good" and "bad" grantId, had the bad one removed, and left the good one. I'm going to go ahead and close this.

**Comment by bswhite** [comment]
@andrewelamb , this caused by the issue you uncovered [here](https://github.com/Sage-Bionetworks/csbc-pson-dcc/issues/78#issuecomment-635499495) with CA182915 and CA215845 being confused.

The publications that you referred to above [here](https://www.synapse.org/#!Synapse:syn21868591/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODY4NTkxIHdoZXJlIHB1YmxpY2F0aW9uSWQgaW4gKCdzeW4yMTY0NTYxNScsICdzeW4yMTY0ODkxNCcsICdzeW4yMTY0NTYxNCcsICdzeW4yMTY0NTYxNicsICdzeW4yMTY0ODk2NicsICdzeW4yMTY0ODk4NicsICdzeW4yMTY0OTEzNCcsICdzeW4yMTY4MTgyMicsICdzeW4yMTY4MTQzNycsICdzeW4yMTY4MTYyNCcsICdzeW4yMTY4MTYyNicsICdzeW4yMTY0NTYxMicsICdzeW4yMTY0NTYxNycsICdzeW4yMTY0NTYxMycpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==) should all have been assigned to CA182915 ('From Mechanism to Population: Modeling HPV-related Oropharyngeal Carcinogenesis') and they should have been deleted because we decided to remove this grant.

**Comment by bswhite** [comment]
@andrewelamb , I meant to reopen this

**Comment by andrewelamb** [comment]
@bswhite @jaeddy 

This looks to be fixed!
