### ISSUE TITLE
Check consortium annotation for potential ICBP grants

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#75]
From Shannon on May 5th:

> As I was cruising through the staging site I noticed that the number of CSBC grants that you have does not match the number of CSBC grants that I have. As of today we have 31 CSBC awards; 13 U54, 17 U01s and 1 U24. There appears to be 5 extra grants attributed to CSBC. There are some grants that had Synapse pages because they were part of the former ICBP program.

I haven't checked the grants recently to see if this comment is still relevant. If we do have projects that should be part of ICBP, I recommend that we set that value for the `consortium` annotation. We can probably update the portal for now so that those grants are returned in queries... but maybe add them back in later?

**Comment by bswhite** [comment]
The attached file from Shannon from January lists the following ICBP grants

CA194389
CA188383
CA184898
CA184897
CA195469
CA199315
CA188388

@jaeddy I don't understand your comment above. Did you mean "update the portal for now so that those grants are _not_ returned in queries"?

Why not update consortium as you suggest? Do we do that on the live/merged tables or in the etl tables? We should check in with Verena and Jineta before propagating anything forward to the live/merged tables (as opposed to manually editing them).

[Index CSBC Grant Numbers January 2020.xlsx](https://github.com/Sage-Bionetworks/csbc-pson-dcc/files/4670721/Index.CSBC.Grant.Numbers.January.2020.xlsx)

**Comment by bswhite** [comment]
But here is a more recent set of grant numbers from Shannon
CA209997[Grant Number] OR CA209975[Grant Number] OR CA209971[Grant Number] OR CA209992[Grant Number] OR CA209923[Grant Number] OR CA217377[Grant Number] OR CA209891[Grant Number] OR CA209988[Grant Number] OR CA217297[Grant Number] OR CA209978[Grant Number] OR CA215798[Grant Number] OR CA215845[Grant Number] OR CA217376[Grant Number] OR CA217450[Grant Number] OR CA217378[Grant Number] OR CA225088[Grant Number] OR CA220378[Grant Number] OR CA227550[Grant Number] OR CA215709[Grant Number] OR CA215794[Grant Number] OR CA215848[Grant Number] OR CA232382[Grant Number] OR CA232161[Grant Number] OR CA232137[Grant Number] OR CA238720[Grant Number] OR CA238475[Grant Number] OR CA227544[Grant Number] OR CA243007[Grant Number] OR CA231978[Grant Number] OR CA243073[Grant Number] OR CA232216[Grant Number] OR CA243072[Grant Number] OR CA243075[Grant Number] OR CA238728[Grant Number] 

Sent via Julie on May 7, 2020
subject: pubmed search for csbc

**Comment by jaeddy** [comment]
@bswhite 

> Did you mean "update the portal for now so that those grants are not returned in queries"?

Yep. My mistake.

I agree we should add the consortium (and also that we should avoid any automated propagation for now). We should be able to test easily enough by manually editing `consortium` in the merged tables, but I'm not sure what impact that will have on facets. The ICBP options might seem a bit out of place (and I don't know if they'll even work with Alina's viz on the home page).

That said - no harm in trying it out!

**Comment by bswhite** [comment]
I assigned 5 of the 7 above-listed grants to have ICBP consortium:
CA184898
CA184897
CA199315
CA188388
CA195469

Shannon explicitly told us the first 4 needed to be changed to ICBP.

The 2 remaining grants are not in our table (they must have been removed since we started this ticket):
CA194389
CA188383
